# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4
    branches:
      - only: master

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "public/cinderella/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install npm packages
          command: |
            yarn install
          working_directory: ./public/cinderella

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "public/cinderella/package.json" }}

      # webpack build
      - run:
          name: webpack build
          command: |
            yarn run build
          working_directory: ./public/cinderella

      # deploy to firebase
      - run: firebase deploy --project "$FIREBASE_PJ" --token "$FIREBASE_TOKEN"

